/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.Controller;
import domain.Invoice;
import domain.InvoiceItem;
import domain.Order;
import domain.OrderItem;
import domain.Product;
import domain.User;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

import tables.OrderTableModel;
import tables.ProductTableModel;
import tables.TableOrderModel;

/**
 *
 * @author Katica
 */
public class FormInvoice extends javax.swing.JDialog {

    /**
     * Creates new form FormInvoice
     */
    public FormInvoice(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        fillForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PanelSelect = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSelectItem = new javax.swing.JTable();
        btnGenerated = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelSelect.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Orders", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 1, 24))); // NOI18N
        PanelSelect.setForeground(new java.awt.Color(255, 0, 51));

        tblSelectItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSelectItem);

        javax.swing.GroupLayout PanelSelectLayout = new javax.swing.GroupLayout(PanelSelect);
        PanelSelect.setLayout(PanelSelectLayout);
        PanelSelectLayout.setHorizontalGroup(
            PanelSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelectLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelSelectLayout.setVerticalGroup(
            PanelSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelectLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGenerated.setText("Genereted");
        btnGenerated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerated, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(PanelSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerated, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneratedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratedActionPerformed

        int row = tblSelectItem.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select row");
            return;
        }

        TableOrderModel tom = (TableOrderModel) tblSelectItem.getModel();
        int idSelectedOrder = (int) tom.getValueAt(row, 0);
        Order selectedOrder = tom.getOrder(idSelectedOrder);

        double amount = 0;
        for (OrderItem orderItem : selectedOrder.getOrderItems()) {
            amount += orderItem.getQuantityOrder() * orderItem.getProduct().getPriceWithVat();
        }

        

        Invoice invoice = new Invoice();
        invoice.setAmount(amount);

        

        for (OrderItem orderItem : selectedOrder.getOrderItems()) {
            InvoiceItem invoiceItem = new InvoiceItem(invoice, orderItem.getNumberOrderItem(), orderItem.getProduct(), orderItem.getProduct().getPriceWithVat(), orderItem.getQuantityOrder(), orderItem.getProduct().getPriceWithVat() * orderItem.getQuantityOrder());
            invoice.getItems().add(invoiceItem);
        }
        FInvoiceView formeInvoiceView = new FInvoiceView(this, true, invoice);
        formeInvoiceView.setVisible(true);

       

    }//GEN-LAST:event_btnGeneratedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSelect;
    private javax.swing.JButton btnGenerated;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblSelectItem;
    // End of variables declaration//GEN-END:variables

    private void fillForm() throws Exception {
        List<Order> orders = Controller.getInstance().getAllOrders();
        TableOrderModel tom = new TableOrderModel(orders);
        tblSelectItem.setModel(tom);

    }

}
