/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.Controller;
import domain.Manufacturer;
import domain.MeasurementUnit;
import domain.Product;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import session.Session;
import tables.ProductTableModel;

/**
 *
 * @author Korisnik
 */
public class FormProductSearch extends javax.swing.JDialog {

    /**
     * Creates new form FormProductSearch
     */
    public FormProductSearch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);

        fillForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        tblProductSearch = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search");

        tblProductSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "MeasurementUnit", "Price with VAT", "Price without VAT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPane.setViewportView(tblProductSearch);

        btnDetails.setText("Details...");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetails))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDetails)
                        .addGap(0, 328, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int row = tblProductSearch.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select row");
            return;
        } 
            ProductTableModel ptm = (ProductTableModel) tblProductSearch.getModel();
            int idSelectedProduct = (int) ptm.getValueAt(row, 0);
            Product product = ptm.getProduct(idSelectedProduct);
            Session.getInstance().setFormMode(FormMode.VIEW);
            FormNewProduct form = new FormNewProduct(null, true, FormMode.VIEW);
            form.formProductSearch = this;
            form.setProduct(product);
            form.setVisible(true);
        

    }//GEN-LAST:event_btnDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnDetails;
    private javax.swing.JTable tblProductSearch;
    // End of variables declaration//GEN-END:variables

    private void fillForm() {

        try {
           
            List<Product> products = Controller.getInstance().getAllProducts();
            TableModel tm = new ProductTableModel(products);
            tblProductSearch.setModel(tm);
            MeasurementUnit[] measurementUnits = new MeasurementUnit[]{MeasurementUnit.KG, MeasurementUnit.L, MeasurementUnit.PCS};
            JComboBox comboMeasurementUnits = new JComboBox(new DefaultComboBoxModel(measurementUnits));
            TableColumn tc = tblProductSearch.getColumnModel().getColumn(3);
            tc.setCellEditor(new DefaultCellEditor(comboMeasurementUnits));
            
           
    }   catch (Exception ex) {
            Logger.getLogger(FormProductSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
}

  

    void delete(Product product) {
        ProductTableModel ptm = (ProductTableModel) tblProductSearch.getModel();
        ptm.delete(product);
        
    }

    void addProduct(Product product) {
        ProductTableModel ptm = (ProductTableModel) tblProductSearch.getModel();
        ptm.addProduct(product);
    }
    
}